services:
  postgres:
    image: postgres:18
    container_name: my_api_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: my_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    container_name: my_api_mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: my_api
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    logging:
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  postgres_volume:
  db:
