spring.application.name=my_api_server
# ??? ?? ??? ???? ???!
logging.level.root=INFO
logging.level.org.springframework.boot.autoconfigure=INFO
# ??? JMX ?? ?? ??? ?????.
logging.level.javax.management=INFO
logging.level.sun.rmi=INFO